### ISSUE TITLE
基于线特征的重定位

### ISSUE THREAD

**Issue by rantengsky** [HarborC/PL-SLAM#1]
师兄，这个点线SLAM中基于线特征的重定位没有实现是吗？

**Comment by HarborC** [comment]
不好意思，这个部分确实没有实现，目前单目PL-SLAM效果上表现一般，可能有些细节没有顾忌到，不知道您复现出来了吗？最近我又修改了一部分

**Comment by rantengsky** [comment]
我也是最近才开始看PL-SLAM，现在把师兄你的代码研究一下😀




| |
冉腾
|
|
邮箱：rantengsky@163.com
|

签名由 网易邮箱大师 定制

在2019年10月12日 16:20，HarborChen 写道：

不好意思，这个部分确实没有实现，目前单目PL-SLAM效果上表现一般，可能有些细节没有顾忌到，不知道您复现出来了吗？最近我又修改了一部分

**Comment by HarborC** [comment]
好的，感觉有问题的，欢迎讨论

**Comment by rantengsky** [comment]
🤣




| |
冉腾
|
|
邮箱：rantengsky@163.com
|

签名由 网易邮箱大师 定制

在2019年10月13日 15:30，HarborChen 写道：

好的，感觉有问题的，欢迎讨论

**Comment by HarborC** [comment]
这里这项工作完成了重定位的工作，你可以参考一下，加入单目的PL-SLAM当中。[robotseu/ORB_Line_SLAM](https://github.com/robotseu/ORB_Line_SLAM)

**Comment by rantengsky** [comment]
非常感谢！




| |
冉腾
|
|
邮箱：rantengsky@163.com
|

签名由 网易邮箱大师 定制

在2019年11月02日 15:47，HarborChen 写道：

这里这项工作完成了重定位的工作，你可以参考一下，加入单目的PL-SLAM当中。robotseu/ORB_Line_SLAM

**Comment by zcyHHU** [comment]
你好，请问我编译完后才能过后，运行的时候提示
ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loading failure: This is not a correct text file!
Wrong path to vocabulary. 
Falied to open at: Vocabulary/ORBvoc.txt
我打开词袋文件家发现是 ORBvoc.bin 我需要怎么改正呢

**Comment by rantengsky** [comment]
找一个txt文件放进去就行了




| |
冉腾
|
|
邮箱：rantengsky@163.com
|

签名由 网易邮箱大师 定制

在2019年12月20日 11:34，zcyHHU 写道：

你好，请问我编译完后才能过后，运行的时候提示
ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular

Loading ORB Vocabulary. This could take a while...
Vocabulary loading failure: This is not a correct text file!
Wrong path to vocabulary.
Falied to open at: Vocabulary/ORBvoc.txt
我打开词袋文件家发现是 ORBvoc.bin 我需要怎么改正呢

**Comment by HarborC** [comment]
将txt后缀改成bin

**Comment by match08** [comment]
TrackWithMotionModelWithLine、LocalMapping.cc 和 TrackReferenceKeyFrameWithLine 局部Mapline中的获取还存在很多问题，这个也是线条特征还不成功原因所在。lsd获取的线段特征虽然不如点特征，但还是可以的，初始化数量还可以，后面问题就是在track局部Mapline的TrackWithMotionModelWithLine和TrackReferenceKeyFrameWithLine 都不是很成功。

**Comment by chenxiaocongAI** [comment]
大哥，你的優化中，對線特徵的優化，雅可比沒有寫出來啊

**Comment by HarborC** [comment]
g2o中可以不写，会进行数值求导

**Comment by chenxiaocongAI** [comment]
大哥，有进行过双目的修改不



---原始邮件---
发件人: "JIAGANG CHEN"<notifications@github.com&gt;
发送时间: 2020年9月16日(周三) 下午5:14
收件人: "HarborC/PL-SLAM"<PL-SLAM@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"chenxiaocongAI"<348733501@qq.com&gt;;
主题: Re: [HarborC/PL-SLAM] 基于线特征的重定位 (#1)




 
g2o中可以不写，会进行数值求导

**Comment by HarborC** [comment]
没有诶

**Comment by zhanglimincqupt** [comment]
你好，请问有没有代码注释呀？我是个初学者，感觉看不太明白，希望能得到您的帮助
