### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by runwithyourheart** [HarborC/PL-SLAM#2]
你好，我编译完你的程序后，运行时出现以下错误，请问有什么解决的建议吗？谢谢
OpenCV Error: Bad argument (Mask error while detecting lines: please check its dimensions and that data type is CV_8UC1) in detect, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/opencv_contrib/line_descriptor/src/LSDDetector.cpp, line 107
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/opencv_contrib/line_descriptor/src/LSDDetector.cpp:107: error: (-5) Mask error while detecting lines: please check its dimensions and that data type is CV_8UC1 in function detect

已放弃 (核心已转储)

**Comment by HarborC** [comment]
有可能是设定掩膜那里有问题，大概在Tracking.cc当中，
![image](https://user-images.githubusercontent.com/28862505/68066863-c89b4580-fd79-11e9-8ce7-ebbb97820c27.png)

**Comment by runwithyourheart** [comment]
> 有可能是设定掩膜那里有问题，大概在Tracking.cc当中，
> ![image](https://user-images.githubusercontent.com/28862505/68066863-c89b4580-fd79-11e9-8ce7-ebbb97820c27.png)

好的，谢谢，我再看看代码！

**Comment by yanmengting117** [comment]
我也遇到了这个问题，请问你解决了吗

**Comment by HarborC** [comment]
你需要检查mask的大小和你的影像大小是否一致


 
---原始邮件---
发件人: "yanmengting117"<notifications@github.com&gt;
发送时间: 2019年11月8日 16:04:07
收件人: "HarborC/PL-SLAM"<PL-SLAM@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"HarborChen"<1391586089@qq.com&gt;;
主题: Re: [HarborC/PL-SLAM] 运行错误 (#2)



我也遇到了这个问题，请问你解决了吗

**Comment by runwithyourheart** [comment]
> 我也遇到了这个问题，请问你解决了吗



> 你需要检查mask的大小和你的影像大小是否一致
> […](#)
> ---原始邮件--- 发件人: "yanmengting117"<notifications@github.com&gt; 发送时间: 2019年11月8日 16:04:07 收件人: "HarborC/PL-SLAM"<PL-SLAM@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"HarborChen"<1391586089@qq.com&gt;; 主题: Re: [HarborC/PL-SLAM] 运行错误 (#2) 我也遇到了这个问题，请问你解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

读取的mask可能和跑的数据集的图片大小不一致，把mask的尺寸改成和数据集一样就可以了。另外我想问一下博主我跑euroc第一个数据集，跑出来的rmse已经到了0.9多，请问效果不好会不会是因为线的误匹配比较多，或者是其他什么原因？谢谢

**Comment by HarborC** [comment]
存在误匹配，但是线特征自身的精度不高的影响也比较大


 
---原始邮件---
发件人: "runwithyourheart"<notifications@github.com&gt;
发送时间: 2019年11月8日 21:04:41
收件人: "HarborC/PL-SLAM"<PL-SLAM@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"HarborChen"<1391586089@qq.com&gt;;
主题: Re: [HarborC/PL-SLAM] 运行错误 (#2)


 
我也遇到了这个问题，请问你解决了吗
   
你需要检查mask的大小和你的影像大小是否一致
 …
 ---原始邮件--- 发件人: "yanmengting117"<notifications@github.com&gt; 发送时间: 2019年11月8日 16:04:07 收件人: "HarborC/PL-SLAM"<PL-SLAM@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"HarborChen"<1391586089@qq.com&gt;; 主题: Re: [HarborC/PL-SLAM] 运行错误 (#2) 我也遇到了这个问题，请问你解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
读取的mask可能和跑的数据集的图片大小不一致，把mask的尺寸改成和数据集一样就可以了。另外我想问一下博主我跑euroc第一个数据集，跑出来的rmse已经到了0.9多，请问效果不好会不会是因为线的误匹配比较多，或者是其他什么原因？谢谢

**Comment by yanmengting117** [comment]
OpenCV Error: Assertion failed (_map1.size().area() > 0) in remap, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp, line 1728
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/imgwarp.cpp:1728: error: (-215) _map1.size().area() > 0 in function remap

你好，请问您是否知道出现这种错误是什么原因呢？

**Comment by wangq0688** [comment]
In file included from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/optimizable_graph.h:37:0,
                 from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/base_vertex.h:30,
                 from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:37,
                 from /home/wq/PL-SLAM-master/include/Converter.h:27,
                 from /home/wq/PL-SLAM-master/src/Converter.cc:22:
/home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/openmp_mutex.h:30:26: fatal error: ../../config.h: 没有那个文件或目录

你好,在编译是一直卡在这,请问你知道原因吗?

**Comment by HarborC** [comment]
你看他说的这个文件还在么原处么?问题在g2o感觉


 
---原始邮件---
发件人: "wangq0688"<notifications@github.com&gt;
发送时间: 2020年1月6日 15:58:43
收件人: "HarborC/PL-SLAM"<PL-SLAM@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"JIAGANG CHEN"<1391586089@qq.com&gt;;
主题: Re: [HarborC/PL-SLAM] 运行错误 (#2)



In file included from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/optimizable_graph.h:37:0,
 from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/base_vertex.h:30,
 from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:37,
 from /home/wq/PL-SLAM-master/include/Converter.h:27,
 from /home/wq/PL-SLAM-master/src/Converter.cc:22:
 /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/openmp_mutex.h:30:26: fatal error: ../../config.h: 没有那个文件或目录
 
你好,在编译是一直卡在这,请问你知道原因吗?

**Comment by wangq0688** [comment]
> In file included from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/optimizable_graph.h:37:0,
> from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/base_vertex.h:30,
> from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:37,
> from /home/wq/PL-SLAM-master/include/Converter.h:27,
> from /home/wq/PL-SLAM-master/src/Converter.cc:22:
> /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/openmp_mutex.h:30:26: fatal error: ../../config.h: 没有那个文件或目录
> 
> 你好,在编译是一直卡在这,请问你知道原因吗?



> 你看他说的这个文件还在么原处么?问题在g2o感觉
> […](#)
> ---原始邮件--- 发件人: "wangq0688"<notifications@github.com&gt; 发送时间: 2020年1月6日 15:58:43 收件人: "HarborC/PL-SLAM"<PL-SLAM@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"JIAGANG CHEN"<1391586089@qq.com&gt;; 主题: Re: [HarborC/PL-SLAM] 运行错误 (#2) In file included from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/optimizable_graph.h:37:0, from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/base_vertex.h:30, from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:37, from /home/wq/PL-SLAM-master/include/Converter.h:27, from /home/wq/PL-SLAM-master/src/Converter.cc:22: /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/openmp_mutex.h:30:26: fatal error: ../../config.h: 没有那个文件或目录 你好,在编译是一直卡在这,请问你知道原因吗? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

但是  /PL-SLAM-master/Thirdparty/g2o 路径下只有 config.h.in 
本来就没有这个文件,重命名后会出现 
/home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/../../config.h:4:2: error: invalid preprocessing directive #cmakedefine
 #cmakedefine G2O_OPENMP 1
  ^
/home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/../../config.h:5:2: error: invalid preprocessing directive #cmakedefine
 #cmakedefine G2O_SHARED_LIBS 1
  ^

**Comment by wangq0688** [comment]
多谢,我解决问题了

**Comment by HarborC** [comment]
好的

**Comment by yanfeng-tang** [comment]
/home/tangyf/PL-SLAM/include/auxiliar.h:13:50: fatal error: opencv2/line_descriptor/descriptor.hpp: 没有那个文件或目录
请问这个问题该怎么解决了,谢谢

**Comment by HarborC** [comment]
安装opencv的时候，把opencv_contrib也安装上，line_descriptor的包，在opencv_contrib里面

**Comment by fengchen122959** [comment]
编译卡在这里几天了，有解决办法么 我的eigen 版本是3.2.9，用的旧版g2o
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:30:64: error: type/value mismatch at argument 4 in template parameter list for ‘template<class Derived, class Scalar, class OtherScalar, bool EnableIt> struct Eigen::internal::special_scalar_op_base’
                                             EigenBase<Derived> >
                                                                ^
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:30:64: note:   expected a constant of type ‘bool’, got ‘Eigen::EigenBase<Derived>’
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:143:94: error: type/value mismatch at argument 4 in template parameter list for ‘template<class Derived, class Scalar, class OtherScalar, bool EnableIt> struct Eigen::internal::special_scalar_op_base’
     typedef internal::special_scalar_op_base<Derived, Scalar, RealScalar, EigenBase<Derived> > Base;
                                                                                              ^
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:143:94: note:   expected a constant of type ‘bool’, got ‘Eigen::EigenBase<Derived>’
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:144:11: error: ‘Base’ is not a class, namespace, or enumeration
     using Base::operator*;

**Comment by fengchen122959** [comment]
> > In file included from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/optimizable_graph.h:37:0,
> > from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/base_vertex.h:30,
> > from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:37,
> > from /home/wq/PL-SLAM-master/include/Converter.h:27,
> > from /home/wq/PL-SLAM-master/src/Converter.cc:22:
> > /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/openmp_mutex.h:30:26: fatal error: ../../config.h: 没有那个文件或目录
> > 你好,在编译是一直卡在这,请问你知道原因吗?
> 
> > 你看他说的这个文件还在么原处么?问题在g2o感觉
> > […](#)
> > ---原始邮件--- 发件人: "wangq0688"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年1月6日 15:58:43 收件人: "HarborC/PL-SLAM"<[PL-SLAM@noreply.github.com](mailto:PL-SLAM@noreply.github.com)>; 抄送: "Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>;"JIAGANG CHEN"<[1391586089@qq.com](mailto:1391586089@qq.com)>; 主题: Re: [HarborC/PL-SLAM] 运行错误 (#2) In file included from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/optimizable_graph.h:37:0, from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/base_vertex.h:30, from /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/types_six_dof_expmap.h:37, from /home/wq/PL-SLAM-master/include/Converter.h:27, from /home/wq/PL-SLAM-master/src/Converter.cc:22: /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/openmp_mutex.h:30:26: fatal error: ../../config.h: 没有那个文件或目录 你好,在编译是一直卡在这,请问你知道原因吗? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 但是 /PL-SLAM-master/Thirdparty/g2o 路径下只有 config.h.in
> 本来就没有这个文件,重命名后会出现
> /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/../../config.h:4:2: error: invalid preprocessing directive #cmakedefine
> #cmakedefine G2O_OPENMP 1
> ^
> /home/wq/PL-SLAM-master/Thirdparty/g2o/g2o/types/../core/../../config.h:5:2: error: invalid preprocessing directive #cmakedefine
> #cmakedefine G2O_SHARED_LIBS 1
> ^

兄弟你在编译pl-slam时遇到过这个问题么
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:30:64: error: type/value mismatch at argument 4 in template parameter list for ‘template<class Derived, class Scalar, class OtherScalar, bool EnableIt> struct Eigen::internal::special_scalar_op_base’
                                             EigenBase<Derived> >
                                                                ^
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:30:64: note:   expected a constant of type ‘bool’, got ‘Eigen::EigenBase<Derived>’
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:143:94: error: type/value mismatch at argument 4 in template parameter list for ‘template<class Derived, class Scalar, class OtherScalar, bool EnableIt> struct Eigen::internal::special_scalar_op_base’
     typedef internal::special_scalar_op_base<Derived, Scalar, RealScalar, EigenBase<Derived> > Base;
                                                                                              ^
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:143:94: note:   expected a constant of type ‘bool’, got ‘Eigen::EigenBase<Derived>’
/usr/local/include/eigen3/Eigen/src/SparseCore/SparseMatrixBase.h:144:11: error: ‘Base’ is not a class, namespace, or enumeration
     using Base::operator*;

**Comment by HarborC** [comment]
是否可以尝试高版本的eigen
