### ISSUE TITLE
CreateMapLines（）

### ISSUE THREAD

**Issue by LukyBird** [HarborC/PL-SLAM#4]
// 保障不在同一对极平面上
                ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                cv::Mat lineVector2 = (Mat_<float>(2,1) << -keyline2_function(1), keyline2_function(0));
                cv::Mat _ray1Start =  (Mat_<float>(3,1) << keyline1.startPointX, keyline1.startPointY, 1); 
                cv::Mat _ray1End =    (Mat_<float>(3,1) << keyline1.endPointX, keyline1.endPointY, 1);
                cv::Mat R21 = Rcw2 * Rwc1;
                cv::Mat t21 = Rcw2 * ( Rwc2 * tcw2 - Rwc1 * tcw1 );
                cv::Mat t21x = SkewSymmetricMatrix(t21);
                cv::Mat F21 = (K2.t()).inv() * t21x * R21 * K1.inv();
                cv::Mat Th1 = F21*_ray1Start;
                cv::Mat Th1_ = (Mat_<float>(2,1) << -Th1.at<float>(1, 0), Th1.at<float>(0, 0));
                float Result1 =  Th1_.dot(lineVector2) / (norm(Th1_) * norm(lineVector2));
                cv::Mat Th2 = F21*_ray1End;
                cv::Mat Th2_ = (Mat_<float>(2,1) << -Th2.at<float>(1, 0), Th2.at<float>(0, 0));
                float Result2 =  Th2_.dot(lineVector2) / (norm(Th2_) * norm(lineVector2));

                if(abs(Result1)>0.996 || abs(Result2)>0.996)
                {
                    continue;
                }
这一段怎么理解

**Comment by dzqiu** [comment]
請問一下線特征沒有用pluker坐標嗎

**Comment by HarborC** [comment]
本代码中没不是使用pluker坐标
