### ISSUE TITLE
线特征的雅可比矩阵  linearizeOplus()

### ISSUE THREAD

**Issue by fightmoney** [HarborC/PL-SLAM#8]
请问作者将 `EdgeLineProjectXYZ::linearizeOplus()` 写到哪了？
![Screenshot 2021-09-26 10:41:04](https://user-images.githubusercontent.com/56303528/134791557-cc31617c-e918-4597-9a7c-03858234563e.png)

**Comment by fightmoney** [comment]
@HarborC

**Comment by HarborC** [comment]
数值求导
